# Generated by Django 3.2 on 2022-04-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_portfolio', models.CharField(max_length=200)),
                ('data', models.JSONField(null=True)),
                ('date_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('tick', models.CharField(blank=True, max_length=50)),
                ('price', models.FloatField(null=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('desc', models.TextField(blank=True)),
                ('portfolio', models.ManyToManyField(to='fin.Portfolio')),
            ],
        ),
    ]
