# Generated by Django 3.2 on 2022-05-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0003_alter_portfolio_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='data',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
