# Generated by Django 3.2 on 2022-06-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0004_alter_portfolio_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_return',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='volatility',
            field=models.FloatField(null=True),
        ),
    ]
