# Generated by Django 3.2 on 2022-06-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0006_portfolio_sharp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='data',
        ),
    ]
