# Generated by Django 3.2 on 2022-06-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0008_portfolio_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='colors',
            field=models.TextField(blank=True),
        ),
    ]
